const GET_EVENTS = 'EVENT/GET_EVENTS';
const CREATE_EVENT = 'EVENT/CREATE_EVENT';
const GET_EVENTDETAILS = 'EVENT/GET_EVENTDETAILS';
const UPDATE_EVENT = 'EVENT/UPDATE_EVENT';
const REMOVE_EVENT = 'EVENT/REMOVE_EVENT';
const SET_SELECTED_EVENT = 'EVENT/SET_SELECTED_EVENT';

const actionTypes = {
  GET_EVENTS,
  CREATE_EVENT,
  GET_EVENTDETAILS,
  UPDATE_EVENT,
  REMOVE_EVENT,
  SET_SELECTED_EVENT,
};

export default actionTypes;
